version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    container_name: local-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: initdb
      MYSQL_USER: user
      MYSQL_PASSWORD: peg_game
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  backend:
    build: ./peg-game-java
    container_name: peg_game_java
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
  frontend:
    build: ./peg-game-vue
    container_name: peg_game_vue
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - backend